# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

name: sim

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - importlib_metadata
  - pip
  - cmake
  - make
  - pip:
      - --extra-index-url https://pypi.nvidia.com
      - isaacsim[all,extscache]==5.1.0
      - torch==2.7.0
      - torchvision==0.22.0
      - black
      - -e .