from typing import Any

def create_prim(
    prim_path: str,
    prim_type: str | None = ...,
    translation: Any | None = ...,
    orientation: Any | None = ...,
    scale: Any | None = ...,
    usd_path: str | None = ...,
    semantic_label: str | None = ...,
    semantic_type: str = ...,
    attributes: dict[str, Any] | None = ...,
) -> Any: ...
def define_prim(prim_path: str, prim_type: str = ...) -> Any: ...
def get_prim_at_path(prim_path: str) -> Any: ...
def is_prim_path_valid(prim_path: str) -> bool: ...
def delete_prim(prim_path: str) -> None: ...
def get_prim_type_name(prim_path: str) -> str: ...
def get_prim_object_type(prim_path: str) -> str: ...
def get_prim_parent(prim: Any) -> Any: ...
def get_prim_children(prim: Any) -> list[Any]: ...
